# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shebei',
            fields=[
                ('shebei_id', models.AutoField(primary_key=True, serialize=False)),
                ('factory', models.CharField(blank=True, max_length=32, null=True, verbose_name='厂')),
                ('department', models.CharField(blank=True, max_length=32, null=True, verbose_name='部门')),
                ('shebeiN', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备名称')),
                ('contacts', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系人姓名')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机')),
                ('tel', models.CharField(blank=True, max_length=32, null=True, verbose_name='座机')),
                ('recipients', models.TextField(blank=True, null=True, verbose_name='收件人')),
                ('makeACopy', models.TextField(blank=True, null=True, verbose_name='抄送')),
                ('shebeRemarks', models.TextField(blank=True, null=True, verbose_name='设备的备注')),
            ],
            options={
                'ordering': ['shebeiN'],
            },
        ),
        migrations.CreateModel(
            name='tongdao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='IP地址')),
                ('tongdaoN', models.CharField(blank=True, max_length=32, null=True, verbose_name='通道名称')),
                ('tongdaoFull', models.CharField(blank=True, max_length=32, null=True, verbose_name='通道全称')),
                ('description', models.CharField(blank=True, max_length=32, null=True, verbose_name='描述')),
                ('sheetName', models.CharField(blank=True, max_length=32, null=True, verbose_name='fromSheets')),
                ('instance', models.CharField(blank=True, max_length=32, null=True)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('tongdao_type_id', models.IntegerField(choices=[(0, '一般通道'), (1, '重要通道')], default=0, null=True, verbose_name='通道重要程度')),
                ('shebeiPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisChannel.shebei')),
            ],
            options={
                'ordering': ['tongdaoN'],
            },
        ),
    ]
