# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-04 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisChannel', '0002_auto_20171105_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tongdao',
            old_name='shebeiPoint',
            new_name='sb_id',
        ),
    ]
