# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-04 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisChannel', '0003_auto_20171105_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shebei',
            name='factory',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工厂'),
        ),
    ]
