# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisChannel', '0004_auto_20171105_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contacts', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系人姓名')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机')),
                ('tel', models.TextField(blank=True, null=True, verbose_name='座机')),
            ],
            options={
                'verbose_name_plural': '联系人',
                'ordering': ['contacts'],
                'verbose_name': '联系人',
            },
        ),
        migrations.AlterModelOptions(
            name='shebei',
            options={'ordering': ['shebeiN'], 'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterModelOptions(
            name='tongdao',
            options={'ordering': ['tongdaoN'], 'verbose_name': '通道', 'verbose_name_plural': '通道'},
        ),
        migrations.RemoveField(
            model_name='shebei',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='shebei',
            name='makeACopy',
        ),
        migrations.RemoveField(
            model_name='shebei',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='shebei',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='shebei',
            name='tel',
        ),
        migrations.AlterField(
            model_name='tongdao',
            name='sb_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fisChannel.shebei', verbose_name='设备id'),
        ),
        migrations.AlterField(
            model_name='tongdao',
            name='tongdaoN',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='设备名称'),
        ),
    ]
