# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-11 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisChannel', '0006_contact_contactremarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tongdao',
            old_name='sb_id',
            new_name='sb',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactRemarks',
            field=models.TextField(blank=True, null=True, verbose_name='联系人的备注'),
        ),
    ]
