# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisChannel', '0007_auto_20171211_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='shebei',
            name='r',
            field=models.ManyToManyField(to='fisChannel.contact', verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='tongdao',
            name='ip',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ip地址'),
        ),
    ]
