# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisChannel', '0008_auto_20171214_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shebei',
            name='r',
            field=models.ManyToManyField(blank=True, null=True, to='fisChannel.contact', verbose_name='联系人'),
        ),
    ]
