# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-31 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisChannel', '0009_auto_20171218_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_lower',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱'),
        ),
    ]
