# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('writer', models.CharField(blank=True, max_length=32, null=True, verbose_name='作者')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'ordering': ['content'],
                'verbose_name_plural': '博客',
                'verbose_name': '博客',
            },
        ),
    ]
